Repository iac-io/myiac, pull requests merged in 2021-01, with the labels that each got.

#34 docker: Rewritten Dockerfile
  Dockerfile
Labels: Fix

#32 Fixes #30 #31: Fixed Cluster creation/deletion. Added GCS Bucket support
  README.md
  build.sh
  cloudbuild.yaml
  cmd/myiac/myiac.go
  go.mod
  internal/cli/cli.go
  internal/cli/create_certificate.go
  internal/cli/create_secret.go
  internal/cli/provider.go
  internal/cli/setup_environment.go
  internal/cluster/cluster.go
  internal/cluster/kubernetes.go
  internal/cluster/kubernetes_test.go
  internal/deploy/deploy.go
  internal/deploy/helm.go
  internal/deploy/helm_test.go
  internal/deploy/terraform.go
  internal/docker/docker.go
  internal/encryption/encrypter.go
  internal/gcp/bucket.go
  internal/gcp/gcp.go
  internal/gcp/kms.go
  internal/gcp/kms_test.go
  internal/gcp/service_account.go
  internal/preferences/preferences.go
  internal/preferences/preferences_test.go
  internal/secret/secret_manager.go
  internal/secret/secret_manager_test.go
  internal/ssl/certificate.go
  internal/ssl/certificate_test.go
  internal/terraform/cluster/cluster.tf
  internal/terraform/cluster/cluster.tfvars
  internal/util/util.go
  testutil/fake_cmd_runner.go
Labels: Fix, bug, enhancement

#39 chore: Ran linter to bring the code to nicly formatted state
  cmd/myiac/myiac.go
  internal/cli/create_certificate.go
  internal/cli/create_secret.go
  internal/cli/setup_environment.go
  internal/cluster/cluster.go
  internal/cluster/kubernetes.go
  internal/cluster/kubernetes_test.go
  internal/commandline/commandline.go
  internal/deploy/deploy.go
  internal/deploy/helm.go
  internal/deploy/helm_test.go
  internal/deploy/terraform.go
  internal/elasticsearch/es.go
  internal/encryption/encrypter.go
  internal/gcp/bucket.go
  internal/gcp/dns.go
  internal/gcp/dns_test.go
  internal/gcp/identity.go
  internal/gcp/kms.go
  internal/gcp/kms_test.go
  internal/gcp/service_account.go
  internal/gcp/service_account_test.go
  internal/preferences/preferences.go
  internal/preferences/preferences_test.go
  internal/properties/properties.go
  internal/secret/secret_manager.go
  internal/secret/secret_manager_test.go
  internal/ssl/certificate.go
  internal/ssl/certificate_test.go
  internal/util/json.go
  internal/util/util.go
  internal/util/yaml.go
  testutil/fake_cmd_runner.go
Labels: chore

#41 Return interfaces instead of struct pointers
  go.sum
  internal/cluster/kubernetes.go
  internal/commandline/commandline.go
  internal/gcp/identity.go
  internal/gcp/kms.go
  internal/gcp/kms_test.go
  internal/gcp/service_account.go
  internal/preferences/preferences.go
  internal/preferences/preferences_test.go
  internal/secret/secret_manager.go
  internal/secret/secret_manager_test.go
  internal/ssl/certificate.go
  internal/ssl/certificate_test.go
  testutil/fake_cmd_runner.go
Labels: chore

#45 helm: Fixed helm repo install
  internal/cli/cli.go
  internal/cloudflare/cloudflare_client.go
  internal/cluster/cluster.go
  internal/terraform/cluster/cluster.tf
  internal/terraform/cluster/init.sh
  internal/terraform/dns/dns.tf
Labels: bug, chore, helm

#48 auth: Fixed authentication to be done before bucket existence check
  Dockerfiles/Dockerfile
  Dockerfiles/container-files/home/app/.p10k.zsh
  Dockerfiles/container-files/home/app/.zshrc
  build-docker.sh
  build.sh
  internal/cli/cli.go
  internal/cli/provider.go
  start-dev-env.sh
Labels: Docker, bug, enhancement

#53 Split out kubernetes secret manager
  internal/cli/create_secret.go
  internal/cloudflare/cloudflare_client_test.go
  internal/cluster/kubernetes.go
  internal/deploy/helm_test.go
  internal/secret/kubernetes_secret_runner.go
  internal/secret/kubernetes_secret_runner_test.go
  internal/secret/secret_manager.go
  internal/secret/secret_manager_test.go
  internal/ssl/certificate_test.go
Labels: chore

#54 fix: setupEnvironment: Fixed option to set kubectl context correctly
  internal/cli/cli.go
  internal/cli/create_certificate.go
  internal/cli/create_secret.go
  internal/cli/setup_environment.go
  internal/cluster/cluster.go
  internal/cluster/provider.go
Labels: Fix, GCP, bug

#57 bug: terraform: node-pool: shortened pool name to have default-pool name
  internal/cli/create_secret.go
  internal/cluster/cluster.go
  internal/terraform/cluster/cluster.tf
  internal/terraform/cluster/cluster.tfvars
  internal/terraform/cluster/variables.tf
Labels: Fix, bug, terraform

#59 cicd: simple go actions job
  .github/workflows/go.yml
Labels: CI/CD

#62 Part1: Added base CI build and test
  .github/workflows/go.yml
  Dockerfiles/Dockerfile
  Dockerfiles/container-files/home/app/.zshrc
  README.md
Labels: CI/CD, chore

#63 terraform: Custom terraform path option (argument) + Enabled tests
  .github/workflows/go.yml
  .gitignore
  internal/cli/cli.go
  internal/cloudflare/cloudflare_client_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/gcp/dns_test.go
  internal/gcp/kms_test.go
  start-dev-env.sh
Labels: CI/CD, terraform

#65 setupEnvironment: GCP: zone arg
  internal/cli/cli.go
  internal/cluster/cluster.go
Labels: Fix, GCP

#68 Custom helm path added to the script
  start-dev-env.sh
Labels: enhancement, helm

#69 resizePool Option
  Dockerfiles/Dockerfile
  Dockerfiles/container-files/home/app/.p10k.zsh
  Dockerfiles/container-files/home/app/.zshrc
  internal/cli/cli.go
  internal/cluster/provider.go
  internal/gcp/gcp.go
Labels: GCP, cli, enhancement

#71 cicd: test code coverage
  .github/workflows/go.yml
  README.md
  codecov.yml
Labels: CI/CD, chore
